// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpjtCpsUc5Z1nrKlIyfY0kdmYtlMIXZ1M',
    appId: '1:639552841489:web:5fcec502fdc09d531eceb0',
    messagingSenderId: '639552841489',
    projectId: 'mes-notes-flutter',
    authDomain: 'mes-notes-flutter.firebaseapp.com',
    storageBucket: 'mes-notes-flutter.appspot.com',
    measurementId: 'G-HF7Q3ZWJ9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfc3mPMp3rY3du4OCZ71WNU6hiWCXDB_A',
    appId: '1:639552841489:android:778765df49db59d91eceb0',
    messagingSenderId: '639552841489',
    projectId: 'mes-notes-flutter',
    storageBucket: 'mes-notes-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQw27UkAjj3R3eZMcShM2GJsrXB19aiCw',
    appId: '1:639552841489:ios:6073612204647a681eceb0',
    messagingSenderId: '639552841489',
    projectId: 'mes-notes-flutter',
    storageBucket: 'mes-notes-flutter.appspot.com',
    iosBundleId: 'dz.djmsamy.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQw27UkAjj3R3eZMcShM2GJsrXB19aiCw',
    appId: '1:639552841489:ios:9986d302bde9d4081eceb0',
    messagingSenderId: '639552841489',
    projectId: 'mes-notes-flutter',
    storageBucket: 'mes-notes-flutter.appspot.com',
    iosBundleId: 'dz.djmsamy.mynotes.RunnerTests',
  );
}
