class DataBaseAlreadyOpen implements Exception {}
class UnableToGetClassDirectory implements Exception {}
class DataBaseAlreadyClose implements Exception {}
class CouldNotDeleteUser implements Exception {}
class UserAlreadyExists implements Exception {}
class CouldNotFindUser implements Exception {}
class CouldNotDeleteNote implements Exception {}
class CouldNotFindNote implements Exception {}
class CouldNotUpdateNote implements Exception {}